server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: baitabei-competition-backend
  mail:
    host: smtp.qq.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zetr6k5v321uzf38ko.mysql.rds.aliyuncs.com:3306/baitabei_2025?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Redis
  redis:
    host: ${REDIS_HOST:39.106.56.69}        # 如 Redis 在 Docker，可改为 127.0.0.1 或 host.docker.internal
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

  # 文件上传
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
      enabled: true

# MyBatis-Plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/*.xml

# JWT
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
  refresh-expiration: 604800000

# 阿里云 OSS
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID:}
    access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET:}
    bucket-name: baitabei
    url-prefix: https://baitabei-2025.oss-cn-beijing.aliyuncs.com/

springfox:
  documentation:
    enabled: false
## Knife4j
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn
#    enable-version: true
#    enable-swagger-models: true
#    enable-document-manage: true
#    swagger-model-name: 实体类列表

# 日志
logging:
  level:
    com.baitabei: debug
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/baitabei-competition.log
    max-size: 10MB
    max-history: 30

# 自定义业务配置
app:
  upload:
    path: /data/upload/
  cors:
    allowed-origins: http://localhost:3000,http://localhost:5173,https://gf2h8yg38227.space.minimax.io,https://h15amiaszznx.space.minimax.io
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: '*'
    allow-credentials: true

  evaluation:
    criteria:
      creativity: 30
      practicality: 25
      technology: 20
      market: 15
      culture: 10